introduce aspect
This does not work due to that `findFirst()` is a blocking call, giving me the following error
```
java.lang.IllegalStateException: Iterating over a toIterable() / toStream() is blocking, which is not supported in thread webflux-http-nio-2
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:168)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP GET "/test" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at reactor.core.publisher.BlockingIterable$SubscriberIterator.hasNext(BlockingIterable.java:168)
		at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1949)
		at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
		at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
		at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
		at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:687)
		at com.example.EventAspect.validateEventDocumentAfterLoad(EventAspect.java:25)
		at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
		at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```